export enum RegulatorySource {
  SEC = 'SEC',
  CFTC = 'CFTC',
  FINCEN = 'FINCEN',
  FATF = 'FATF',
  ESMA = 'ESMA',
  FCA = 'FCA',
  MAS = 'MAS',
  HKMA = 'HKMA',
  JFSA = 'JFSA',
  OTHER = 'OTHER'
}

export enum ChangeType {
  NEW_REGULATION = 'NEW_REGULATION',
  AMENDMENT = 'AMENDMENT',
  REPEAL = 'REPEAL',
  GUIDANCE = 'GUIDANCE',
  ENFORCEMENT = 'ENFORCEMENT',
  POLICY_UPDATE = 'POLICY_UPDATE'
}

export enum ImpactLevel {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  MINIMAL = 'MINIMAL'
}

export enum TaskStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED'
}

export enum TaskPriority {
  URGENT = 'URGENT',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW'
}

export enum ComplianceArea {
  KYC = 'KYC',
  AML = 'AML',
  REPORTING = 'REPORTING',
  LICENSING = 'LICENSING',
  PRIVACY = 'PRIVACY',
  DATA_PROTECTION = 'DATA_PROTECTION',
  CAPITAL_REQUIREMENTS = 'CAPITAL_REQUIREMENTS',
  RISK_MANAGEMENT = 'RISK_MANAGEMENT',
  CONSUMER_PROTECTION = 'CONSUMER_PROTECTION',
  MARKET_INTEGRITY = 'MARKET_INTEGRITY'
}

export interface RegulatoryChange {
  id: string;
  title: string;
  summary: string;
  content: string;
  source: RegulatorySource;
  sourceUrl?: string;
  changeType: ChangeType;
  publicationDate: Date;
  effectiveDate?: Date;
  relevanceScore: number;
  impactLevel?: ImpactLevel;
  jurisdictions: string[];
  complianceAreas: ComplianceArea[];
  aiTags?: string[];
  isProcessed: boolean;
  isAssessed: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ImpactAssessment {
  id: string;
  regulatoryChangeId: string;
  assessorId: string;
  assessorName: string;
  impactLevel: ImpactLevel;
  impactSummary: string;
  affectedOperations: string[];
  requiredActions: string[];
  estimatedCost?: number;
  estimatedTimeline?: number; // days
  riskFactors: string[];
  recommendations: string[];
  status: string;
  approvedBy?: string;
  approvedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComplianceTask {
  id: string;
  regulatoryChangeId: string;
  title: string;
  description: string;
  complianceArea: ComplianceArea;
  assignedTo?: string;
  assignedToName?: string;
  status: TaskStatus;
  priority: TaskPriority;
  dueDate?: Date;
  completedAt?: Date;
  estimatedHours?: number;
  actualHours?: number;
  dependencies?: string[];
  checklist?: string[];
  notes?: string[];
  attachments?: string[];
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface PolicyUpdate {
  id: string;
  regulatoryChangeId: string;
  policyName: string;
  policyType: string;
  oldContent?: string;
  newContent: string;
  changeSummary: string;
  updateType: string; // CREATE, UPDATE, DELETE
  autoGenerated: boolean;
  reviewedBy?: string;
  approvedBy?: string;
  status: string;
  effectiveDate?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface AuditTrailEntry {
  id: string;
  regulatoryChangeId: string;
  action: string;
  actorId: string;
  actorName: string;
  actorRole: string;
  details: any;
  previousState?: any;
  newState?: any;
  ipAddress?: string;
  userAgent?: string;
  timestamp: Date;
}

export interface ComplianceTeam {
  id: string;
  name: string;
  email: string;
  role: string;
  department: string;
  expertise: ComplianceArea[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface RegulatorySubscription {
  id: string;
  name: string;
  source: RegulatorySource;
  feedUrl: string;
  apiKey?: string;
  isActive: boolean;
  lastFetchedAt?: Date;
  fetchFrequency: number; // seconds
  filters?: any;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComplianceTemplate {
  id: string;
  name: string;
  description: string;
  complianceArea: ComplianceArea;
  templateType: string;
  content: any;
  variables?: any;
  isActive: boolean;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface RelevanceScoreResult {
  score: number;
  confidence: number;
  factors: {
    keywordMatch: number;
    jurisdictionRelevance: number;
    complianceAreaMatch: number;
    recency: number;
    sourceAuthority: number;
  };
  explanation: string;
  suggestedTags: string[];
}

export interface ImpactAssessmentWorkflow {
  regulatoryChangeId: string;
  currentStep: string;
  steps: Array<{
    name: string;
    status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'SKIPPED';
    assignedTo?: string;
    completedAt?: Date;
    notes?: string;
  }>;
  estimatedCompletion: Date;
  blockers: string[];
}

export interface ComplianceMetrics {
  totalChanges: number;
  pendingAssessments: number;
  overdueTasks: number;
  completedTasks: number;
  averageAssessmentTime: number; // hours
  averageTaskCompletionTime: number; // hours
  complianceScore: number; // 0-100
  riskDistribution: Record<ImpactLevel, number>;
  workloadByTeam: Record<string, number>;
}

export interface RegulatoryDashboard {
  summary: ComplianceMetrics;
  recentChanges: RegulatoryChange[];
  urgentTasks: ComplianceTask[];
  upcomingDeadlines: ComplianceTask[];
  highImpactChanges: RegulatoryChange[];
  teamWorkload: Array<{
    teamMember: string;
    activeTasks: number;
    overdueTasks: number;
    utilization: number;
  }>;
  trends: {
    changesOverTime: Array<{ date: string; count: number }>;
    assessmentTimes: Array<{ week: string; averageTime: number }>;
    complianceScore: Array<{ month: string; score: number }>;
  };
}
